const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const generatePDF = (title, summary) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({
                size: 'A4',
                margin: 50
            });

            const fileName = `${Date.now()}_lecture.pdf`;
            const filePath = path.join(__dirname, '..', 'downloads', fileName);

            // Ensure downloads directory exists
            const downloadsDir = path.join(__dirname, '..', 'downloads');
            if (!fs.existsSync(downloadsDir)) {
                fs.mkdirSync(downloadsDir);
            }

            const stream = fs.createWriteStream(filePath);
            doc.pipe(stream);

            // Add header with title
            doc.font('Helvetica-Bold')
                .fontSize(20)
                .text(title, { align: 'center' });

            doc.moveDown(2);

            // Add "Lecture Summary" subtitle
            doc.font('Helvetica-Bold')
                .fontSize(16)
                .text('Lecture Summary', { align: 'left' });

            doc.moveDown();

            // Process and add bullet points
            const bulletPoints = summary.split('\n').filter(point => point.trim());
            
            doc.font('Helvetica')
                .fontSize(12)
                .lineGap(10);

            bulletPoints.forEach(point => {
                // Remove any existing bullet points or dashes
                let cleanPoint = point.replace(/^[•\-\*]\s*/, '').trim();
                
                // Add bullet points with proper formatting
                doc.text(`• ${cleanPoint}`, {
                    indent: 20,
                    align: 'left',
                    lineGap: 10
                });
            });

            // Add footer
            doc.moveDown(4);
            doc.fontSize(10)
                .text('Generated by GenFlex', {
                    align: 'center',
                    color: 'grey'
                });

            // Finalize PDF
            doc.end();

            stream.on('finish', () => {
                resolve(fileName);
            });

            stream.on('error', (error) => {
                reject(error);
            });

        } catch (error) {
            reject(error);
        }
    });
};

module.exports = { generatePDF };