// pdfGenerator.js
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

// Fixed generateExamPDF in pdfGenerator.js - properly displays duration in PDF

const generateExamPDF = (title, questions, includeAnswers = false, duration = 120) => {
    return new Promise((resolve, reject) => {
        try {
            // Make sure duration is a number
            duration = parseInt(duration) || 120;
            
            const doc = new PDFDocument({
                size: 'A4',
                margin: 50,
                bufferPages: true
            });

            const fileName = `${Date.now()}_exam.pdf`;
            const filePath = path.join(__dirname, '..', 'downloads', fileName);

            // Ensure downloads directory exists
            const downloadsDir = path.join(__dirname, '..', 'downloads');
            if (!fs.existsSync(downloadsDir)) {
                fs.mkdirSync(downloadsDir, { recursive: true });
            }

            const stream = fs.createWriteStream(filePath);
            doc.pipe(stream);

            // Add header
            doc.fontSize(16)
               .font('Helvetica-Bold')
               .text(title, { align: 'center' });

            doc.moveDown();
            doc.fontSize(12)
               .font('Helvetica')
               .text('Essay Questions', { align: 'center' });

            // Add time limit - with clear formatting
            doc.moveDown();
            doc.fontSize(12)
               .font('Helvetica-Bold')
               .text(`Time Limit: ${formatDuration(duration)}`, { align: 'center' });

            doc.moveDown();

            // Add instructions
            doc.fontSize(11)
               .font('Helvetica')
               .text('Instructions: Read all questions carefully. Answer all questions within the given time limit. The timer starts once you begin the exam.', { align: 'left' });

            doc.moveDown();

            // Add questions with proper spacing and page breaks
            questions.forEach((qa, index) => {
                // Check if we need to add a new page
                if (doc.y > 700) {
                    doc.addPage();
                }

                // Question number and text
                doc.font('Helvetica-Bold')
                   .fontSize(12)
                   .text(`Question ${index + 1}:`, { continued: false });

                doc.font('Helvetica')
                   .fontSize(11)
                   .text(qa.question, {
                       lineGap: 2,
                       paragraphGap: 5,
                       width: doc.page.width - 100,
                       align: 'justify'
                   });

                doc.moveDown();

                // Add answer section
                if (includeAnswers && qa.answer) {
                    doc.font('Helvetica-Bold')
                       .fontSize(11)
                       .text('Answer:', { continued: false });
                       
                    doc.font('Helvetica')
                       .fontSize(11)
                       .text(qa.answer, {
                           lineGap: 2,
                           paragraphGap: 5,
                           width: doc.page.width - 100,
                           align: 'justify'
                       });
                } else {
                    // Add answer space
                    doc.font('Helvetica-Bold')
                       .fontSize(11)
                       .text('Answer:', { continued: false });

                    // Add lines for writing
                    const lineCount = 5;
                    for (let i = 0; i < lineCount; i++) {
                        doc.moveDown(0.5);
                        doc.lineCap('butt')
                           .moveTo(50, doc.y)
                           .lineTo(doc.page.width - 50, doc.y)
                           .stroke();
                    }
                }

                doc.moveDown(2);
            });

            // Add page numbers
            let pages = doc.bufferedPageRange();
            for (let i = 0; i < pages.count; i++) {
                doc.switchToPage(i);
                
                // Page number
                doc.fontSize(10)
                   .text(
                       `Page ${i + 1} of ${pages.count}`,
                       0,
                       doc.page.height - 50,
                       { align: 'center' }
                   );
            }

            // Footer on last page
            doc.switchToPage(pages.count - 1);
            doc.fontSize(10)
               .text(
                   `Generated by GenFlex - ${new Date().toLocaleDateString()}`,
                   0,
                   doc.page.height - 30,
                   { align: 'center' }
               );

            doc.end();

            stream.on('finish', () => {
                resolve(fileName);
            });

            stream.on('error', (error) => {
                reject(error);
            });

        } catch (error) {
            reject(error);
        }
    });
};

// Helper function to format duration in minutes to a human-readable format
function formatDuration(minutes) {
    if (typeof minutes !== 'number') {
        minutes = parseInt(minutes) || 120;
    }
    
    if (minutes >= 60) {
        const hours = Math.floor(minutes / 60);
        const remainingMinutes = minutes % 60;
        return `${hours} ${hours === 1 ? 'hour' : 'hours'}${remainingMinutes > 0 ? ` ${remainingMinutes} minutes` : ''}`;
    } else {
        return `${minutes} minutes`;
    }
}

module.exports = { generateExamPDF };